service:
  name: cryptor

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 1024
  timeout: 10
  stage: dev
  alias: dev

functions:
  postMonoalphabetic:
    handler: src/service/handlers/post.monoHandler
    events:
      - http:
          method: post
          path: mono

  postPolyalphabetic:
    handler: src/service/handlers/post.polyHandler
    events:
      - http:
          method: post
          path: poly
