service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs8.10

functions:
  postMonoalphabetic:
    handler: src/service/handlers/post.handler
    events:
      - http:
          method: post
          path: mono
